### ISSUE TITLE
[@if false]  doesn't seem to work

### ISSUE THREAD

**Issue by edwintorok** [ocamllibs/metapp#9]
The example from the manual is out-of-date, I got this syntax to compile (based on the syntax I found in the tests):
```
[%%meta (new Metapp.filter)#structure_item
[%stri
  type t = AX
    | BX [@if false]
]
]
let cx = BX
```

However the `BX` variant should've been removed and created a compile error, and it hasn't.
This is on OCaml 4.14.1. What am I doing wrong?

(and similarly for record fields it compiles but doesn't remove the field)

**Comment by edwintorok** [comment]
(as a workaround the entire type declaration can be repeated twice,once with and without the variant, but this becomes tedious for large variant types, or records with lots of fields)

**Comment by thierry-martinez** [comment]
Thank you very much, @edwintorok : indeed, the example in the manual is out of date, and I forgot to implement the filtering on type declaration. Thank you for reporting this and for your pull request!
